version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
