on: push
name: Unit tests
jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        coverage: none
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Run unit tests
      run: |
        vendor/bin/phpunit
